# Generated by Django 5.0.6 on 2024-07-14 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_fornecedor_cnpj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='quantidade',
        ),
        migrations.AlterField(
            model_name='estoque',
            name='produto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.produto'),
        ),
    ]
