# Generated by Django 5.0.6 on 2024-07-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_estoque_quantidade_alter_estoque_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data Atualização'),
        ),
    ]
