# Generated by Django 5.0.6 on 2024-07-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_estoque_data_atualizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaestoque',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data Atualização'),
        ),
        migrations.AlterField(
            model_name='saidaestoque',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
