# Generated by Django 5.1.2 on 2024-10-19 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaSaidaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('quantidade', models.SmallIntegerField()),
                ('ordem', models.CharField(choices=[('Entrada', 'Entrada'), ('Saida', 'Saida')], max_length=7)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto')),
            ],
            options={
                'ordering': ('-data',),
            },
        ),
    ]
