# Generated by Django 5.1.2 on 2024-10-19 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da empresa')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('telefone', models.CharField(max_length=16)),
                ('endereco', models.CharField(max_length=255, verbose_name='endereço')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome do Produto')),
                ('estoque_minimo', models.PositiveSmallIntegerField(verbose_name='Estoque mínimo')),
                ('preco_custo', models.FloatField(verbose_name='Preço de custo')),
                ('preco_venda', models.FloatField(verbose_name='Preço de venda')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='produtos_img/', verbose_name='Imagem do Produto')),
                ('ativo', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='observação')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.categoria')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.fornecedor')),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
    ]
